name: Start Up Discord Bot  

on:
  schedule:
    - cron: '0 */6 * * *'
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      input-parameter-name:
        description: 'Description of the input parameter'
        required: true
        default: 'Default value'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.18

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Python script
      run: python main.py
      env:
        STAFF_LIST: ${{ secrets.STAFF_LIST }}
        SERVICEID: ${{ secrets.SERVICEID }}
        USER_IDENTITY: ${{ secrets.USER_IDENTITY }}
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}

  manual-trigger:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Manual trigger step
        run: echo "This workflow was manually triggered"
